name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Zde nastavte název větve, ze které chcete nasazovat

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Nastavte verzi Node.js podle potřeby

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # Pokud používáte buildovací nástroj, jinak tuto část přizpůsobte

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Změňte cestu podle toho, kde máte buildované soubory
